#!/bin/sh
BROWSERIFY="node_modules/.bin/browserify --debug --detect-globals false"
BUNDLE_EXAMPLE="$BROWSERIFY -t reactify -x react -x react-modal"
NODE_ENV=development $BROWSERIFY -t reactify -t envify -r react -r ./lib:react-modal > examples/global-bundle.js

$BUNDLE_EXAMPLE examples/basic/app.js > examples/basic/app-bundle.js
